### ISSUE TITLE
Admin page broken when trying to access inventory change page

### ISSUE THREAD

**Issue by s-lee-kwong** [chisomiloks/logiistics-inventory-app#1]
http://127.0.0.1:8000/admin/inventory/inventory/3/change/

Replacing the 3 with whatever inventory ID exists.
<img width="1884" alt="Screen Shot 2022-01-18 at 6 57 56 PM" src="https://user-images.githubusercontent.com/394561/150037967-b6b03343-6091-467f-a078-9a32ef02fb5a.png">

**Comment by chisomiloks** [comment]
Issue fixed. Date fieldset on inventory admin page was cause of error as it is not an editable field.
